### ISSUE TITLE
Generated Mailbox.select borks Eclipse

### ISSUE THREAD

**Issue by shaxbee** [kilim/kilim#29]
It seems that weaver is mutating Mailbox.select(Mailbox... mboxes) to Mailbox.select(Mailbox[] mboxes, Fiber fiber). That confuses Eclipse and causes constant flood of exceptions coming from internal parser / compiler.

``` java
Mailbox<String> foo = new Mailbox<String>();
Mailbox<String> bar = new Mailbox<String>();

Mailbox.select(foo, bar); // kaboom!
```

**Comment by nqzero** [comment]
i'm closing this issue as it's old and likely no longer happens (i don't have an eclipse installation to test with), since the last activity was 4+ years ago

as described, this issue was really a problem (presumably) with eclipse, not kilim. that said, if kilim doesn't work with the popular IDEs then it's utility is limited. so if this problem resurfaces it's something we'd consider trying to work around. in that event, create a new issue
