### ISSUE TITLE
How to create a jdk dynamic proxy calls Pausable method?

### ISSUE THREAD

**Issue by withoutme** [kilim/kilim#50]
I want to create a dynamic proxy, this proxy calls methods which are Pausable.
but throws exception:

java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1342)
	at kilim.Task.errNotWoven(Task.java:231)
	at com.xxx.XXInvocationHandler.invoke(XXInvocationHandler.java)
	at com.sun.proxy.$Proxy17.dotXXX(Unknown Source)

use Proxy.newProxyInstance() to create proxy

"invoke" method in XXInvocationHandler is already declare as Pausable, and is woven

need help!
THANK YOU!

**Comment by sriram-srinivasan** [comment]
Any method that calls a pausable method must itself be pausable (*). This is not just a kilim thing; this is true for any language with async await semantics. 

The best way for non-pausable methods to call pausable methods is to wrap the latter in a Task and  call "joinb"  (blocking join) on it 
So your proxy would look something like this: 

`     class Proxy {
          void callPausableMethod() {
                  t = new Task() {
                      void execute() throws Pausable() {
                            retValue = obj.pausableMethod(); // specify appropriate type of retValue
                            exit(retValue);
                      }
                  ExitMsg m = t.joinb();
                  // extract retValue from exit msg
            }`

**Comment by withoutme** [comment]
Thank you very much!

**Comment by JasonHuangHuster** [comment]
Hi , this method have get a way around the non-weaved problem , but if i put the execution logic inside the `Task Body`, then i will lost the previous Task's context . 
`@Override
    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {

        final Method mtd = method;
        final Object[] ags = args;
        if (!sppCmdMap.containsKey(method.getName())) {
            return null;
        }
        final RpcContext rpcContext = RpcContext.getContext(KilimTask.getCurrentTask().id);
        Task t = new Task() {
            public void execute() throws Exception, Pausable {

                if (!sppCmdMap.containsKey(mtd.getName())) {
                    return;
                }
                RpcCmdInfo cmd = sppCmdMap.get(mtd.getName());
                if (ags[0] instanceof List) {
                    List<Message> reqs = (List<Message>) ags[0];
                    exit(rpcInvokeBatch(reqs, cmd, rpcContext));
                } else {
                    Message req = (Message) ags[0];
                    exit(rpcInvoke(req, cmd, rpcContext));
                }
            }
        };
        t.start();
        ExitMsg m = t.joinb();
        return m.result;
    }
`

here if i want get the previous Task's Context , i have to use `KilimTask.getCurrentTask().id`
but this is a Pausable method ...
is there any good idea to solve this ?
Tks advance ! : )
BTW ,  Kilim is really awesome ! our team is really enjoy with it .

**Comment by kilim** [comment]
Perhaps you can explain the problem you want to solve, and then I can understand your solution and suggest a way out (if there is one). —sriramOn 1 Jul 2017, at 16:22, JasonHuangHuster <notifications@github.com> wrote:Hi , this method have get a way around the non-weaved problem , but if i put the execution logic inside the Task Body, then i will lost the previous Task's context .`@overridepublic Object invoke(Object proxy, Method method, Object[] args) throws Throwable {    final Method mtd = method;    final Object[] ags = args;    if (!sppCmdMap.containsKey(method.getName())) {        return null;    }    final RpcContext rpcContext = RpcContext.getContext(KilimTask.getCurrentTask().id);    Task t = new Task() {        public void execute() throws Exception, Pausable {            if (!sppCmdMap.containsKey(mtd.getName())) {                return;            }            RpcCmdInfo cmd = sppCmdMap.get(mtd.getName());            if (ags[0] instanceof List) {                List<Message> reqs = (List<Message>) ags[0];                exit(rpcInvokeBatch(reqs, cmd, rpcContext));            } else {                Message req = (Message) ags[0];                exit(rpcInvoke(req, cmd, rpcContext));            }        }    };    t.start();    ExitMsg m = t.joinb();    return m.result;}`here if i want get the previous Task's Context , i have to use KilimTask.getCurrentTask().idbut this is a Pausable method ...is there any good idea to solve this ?Tks advance ! : )BTW , Kilim is really awesome ! our team is really enjoy with it .—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kilim/kilim","title":"kilim/kilim","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kilim/kilim"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JasonHuangHuster in #50: Hi , this method have get a way around the non-weaved problem , but if i put the execution logic inside the `Task Body`, then i will lost the previous Task's context . \r\n`@Override\r\n public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {\r\n\r\n final Method mtd = method;\r\n final Object[] ags = args;\r\n if (!sppCmdMap.containsKey(method.getName())) {\r\n return null;\r\n }\r\n final RpcContext rpcContext = RpcContext.getContext(KilimTask.getCurrentTask().id);\r\n Task t = new Task() {\r\n public void execute() throws Exception, Pausable {\r\n\r\n if (!sppCmdMap.containsKey(mtd.getName())) {\r\n return;\r\n }\r\n RpcCmdInfo cmd = sppCmdMap.get(mtd.getName());\r\n if (ags[0] instanceof List) {\r\n List\u003cMessage\u003e reqs = (List\u003cMessage\u003e) ags[0];\r\n exit(rpcInvokeBatch(reqs, cmd, rpcContext));\r\n } else {\r\n Message req = (Message) ags[0];\r\n exit(rpcInvoke(req, cmd, rpcContext));\r\n }\r\n }\r\n };\r\n t.start();\r\n ExitMsg m = t.joinb();\r\n return m.result;\r\n }\r\n`\r\n\r\nhere if i want get the previous Task's Context , i have to use `KilimTask.getCurrentTask().id`\r\nbut this is a Pausable method ...\r\nis there any good idea to solve this ?\r\nTks advance ! : )\r\nBTW , Kilim is really awesome ! our team is really enjoy with it . "}],"action":{"name":"View Issue","url":"https://github.com/kilim/kilim/issues/50#issuecomment-312425231"}}}

**Comment by JasonHuangHuster** [comment]
sorry , i opened a new issue cause this one have closed already ..i've deleted the comment .

**Comment by JasonHuangHuster** [comment]
I want get the Task Id which is invoking the Java Dynamic Proxy InvocationHandler's `invoke` method from inside the `invoke` method body.
