### ISSUE TITLE
Pause specific task? (Especially from within another Task)

### ISSUE THREAD

**Issue by Wonderlus** [kilim/kilim#52]
Is it possible to pause a specific Task, especially from within another Task?

Example:

        Task counterTask = new Task() {
            @Override
            public void execute() throws Pausable {
                for(int i = 1; i <= 100; i++) {
                    Task.sleep(1000L);
                    System.out.println(i);
                }
            }
        }.start();

        Task pauseTask = new Task() {
            @Override
            public void execute() throws Pausable {
                Task.sleep(5000L);
                System.out.println("Pausing counter task...");
                //counterTask.pause(); //<-- this is what I'd like to do.
                Task.sleep(5000L);
                System.out.println("Resuming counter task...");
                counterTask.resume();
            }
        }.start();

**Comment by kilim** [comment]
> Is it possible to pause a specific Task, especially from within another Task?
> 
> 

No.  And you shouldn’t be able to either .. that way lies a lot of pain and madness. The reasons are similar to why Thread.kill() was deprecated, but worse.

What is the higher level objective?

**Comment by Wonderlus** [comment]
> No.  And you shouldn’t be able to either .. that way lies a lot of pain and madness. The reasons are similar to why Thread.kill() was deprecated, but worse.

What is the higher level objective?


So is there no way of doing this at all?


    public static void main(String[] args) {
        if(Kilim.trampoline(false, args))
            return;

        CustomTask counterTask = new CustomTask() {
            @Override
            public void execute() throws Pausable {
                for(int i = 1; i <= 100; i++) {
                    Task.sleep(1000L);
                    System.out.println(i);
                }
            }
        };
        counterTask.start();

        Task pauseTask = new Task() {
            @Override
            public void execute() throws Pausable {
                Task.sleep(5000L);
                System.out.println("Pausing counter task...");
                //counterTask.pause(); //<-- this is what I'd like to do.
                Task.sleep(5000L);
                System.out.println("Resuming counter task...");
                counterTask.resume();
            }
        }.start();

    }

**Comment by Wonderlus** [comment]
What about
`Task.pause(null, counterTask.getFiber()); `
(Even though getFiber() doesn't exist, it could..)

**Comment by kilim** [comment]
> On 5 Jul 2017, at 16:13, Cylus <notifications@github.com> wrote:
> 
> No. And you shouldn’t be able to either .. that way lies a lot of pain and madness. The reasons are similar to why Thread.kill() was deprecated, but worse.
> 
> What is the higher level objective?
> 
> So is there no way of doing this at all?
> 

No.  That is, it is possible to make it happen, but those changes are definitely not going to happen. As I said, in that path lies certain madness. 


You can always send a signal to another task, and that task can make a nonblocking or nonpausing call to see if there’s a signal pending. Since it is cooperative multitasking, the receiving task can always choose to yield or sleep etc.

—s

**Comment by Wonderlus** [comment]
Dang, alright. This was looking clean. Back to Quasar I guess.

**Comment by nqzero** [comment]
if i understand your goal correctly, it can be accomplished using mailboxes. sorry that it took me a while to post this - i found a bug in the process of writing up this example and needed to publish the new version (make sure you're using at least 2.0.0-11)

```
public class Issue52 {
    public static void main(String[] args) {
        if (Kilim.trampoline(false,args))
            return;
        
        boolean dbg = false;
        
        // times to iterate, run and pause, and the number of times to pause and to count
        int tcount=173, trun=1500, tpause=500, npause=40, ncount=100;

        Mailbox<Integer> pause = new Mailbox();
        Mailbox<Integer> resume = new Mailbox();
        
        Task counterTask = new Task() {
            public void execute() throws Pausable {
                for (int i = 1; i <= ncount; i++) {
                    Integer msg = pause.get(tcount);
                    if (msg != null) {
                        Integer rval = resume.get();
                        if (dbg) System.out.println("resumed: " + rval);
                    }
                    System.out.println(i);
                }
                System.exit(0);
            }
        }.start();

        Task pauseTask = new Task() {
            @Override
            public void execute() throws Pausable {
                for (int ii=0; ii < npause; ii++) {
                    Task.sleep(trun);
                    if (dbg) System.out.println("Pausing counter task...");
                    pause.put(0);
                    Task.sleep(tpause);
                    if (dbg) System.out.println("Resuming counter task...");
                    resume.put(0);
                }
            }
        }.start();
    }
}
```

if i misunderstood your goal, let me know

**Comment by Wonderlus** [comment]
@nqzero Let me maybe give you an example of why I would want such a system..

package kilim;

import java.util.ArrayList;
import java.util.concurrent.*;

public class Event {

    private static final class Player {

        private ArrayList<Event> activeEvents = new ArrayList<>();

    }

    public static void main(String[] args) {
        Player player = new Player();

        //a player's active events
        for(int i = 0; i < 5; i++) {
            final int id = i;
            Event event = startEvent(e -> {
                //these events can be a variety of actions ranging from (player movement, interactions, etc)
                //which can also have delays, such as:
                e.delay(1);
                System.out.println("Active: " + id);
                //more actions..
            });
            player.activeEvents.add(event);
        }

        //a teleport event which should pause all active tasks, then resume them.
        startEvent(e -> {
            System.out.println("Pausing active events...");
            //pause all active events until the teleport is over...
            for(Event active : player.activeEvents)
                active.pause();

            System.out.println("Teleporting...");
            //teleport code...
            e.delay(5);
            //end of teleport code...

            System.out.println("Resuming active events...");
            //resume all active events
            for(Event active : player.activeEvents)
                active.resume();
        });
    }

    /**
     * Event
     */

    private static final ConcurrentLinkedQueue<Event> EVENTS = new ConcurrentLinkedQueue<>();

    private static final ScheduledExecutorService EXECUTOR;

    static {
        long tickRate = 600L;
        EXECUTOR = Executors.newSingleThreadScheduledExecutor();
        EXECUTOR.scheduleAtFixedRate(() -> EVENTS.removeIf(event -> !event.tick()), 0L, tickRate, TimeUnit.MILLISECONDS);
    }

    public static Event startEvent(EventConsumer eventConsumer) {
        Event event = new Event(eventConsumer);
        EVENTS.add(event);
        return event;
    }

    private int delayTicks = -1;

    private Task task;

    private Event(EventConsumer consumer) {
        task = new Task() {
            @Override
            public void execute() throws Pausable {
                consumer.accept(Event.this);
            }
        };
    }

    private boolean tick() {
        if(delayTicks == -1) {
            /* requires start */
            delayTicks = 0;
            task.start();
        } else if(delayTicks > 0 && --delayTicks == 0) {
            /* requires resume */
            task.resume();
        }
        return !task.isDone();
    }

    public final void stop() {
        //todo
    }

    public final void pause() throws Pausable {
        //todo
    }

    public final boolean resume() {
        return task.resume();
    }

    public final void delay(int ticks) throws Pausable {
        delayTicks = ticks;
        pause();
    }

    /**
     * Consumer
     */

    @FunctionalInterface
    public interface EventConsumer {
        void accept(Event event) throws Pausable;
    }

}

**Comment by nqzero** [comment]
what you're trying to do is similar to how i'm using kilim. that said, it's hard to get this usage correct and most problems are more easily solved with `Mailbox`es and `Actor`s. but if you want to go this route i can get you started in the "wrong" direction. in your `Event`:

```
    private int delayTicks = -1;
    boolean inactive = false;
    private Continuation task;
    private Event(EventConsumer consumer) {
        task = new Continuation() {
            public void execute() throws Pausable {
                consumer.accept(Event.this);
            }
        };
    }
    private boolean tick() {
        boolean done = false;
        if (inactive) return true;
        if(delayTicks == -1) {
            delayTicks = 0;
            done = task.run();
        }
        else if(delayTicks > 0 && --delayTicks == 0)
            done = task.run();
        return !done;
    }
    public final void pause() throws Pausable { inactive = true; }
    public final void resume() { inactive = false; }
    public final void delay(int ticks) throws Pausable {
        delayTicks = ticks;
        Fiber.yield();
    }
```
the big change here is that you're using `Continuation` directly instead of the higher level `Task`. you're responsible for looping until it finishes, but it gives you total control

note: this won't interrupt methods arbitrarily (which as sriram said can't be done reliably). each method will run until it yields (this is the fundamental unit of work in kilim)

**Comment by kilim** [comment]
There is no framework (quasar included) that will directly let you do this. When a task is running in a thread, the only way to make it stop executing right away is to have the O/S scheduler switch control. But no O/S scheduler gives an API to do that. 

However, an external entity (external to a task)  can _request_ the task itself to “please, suspend yourself until further notice”.  But that means the task has to periodically monitor some mailbox or a shared volatile flag or semaphore to get this signal, and suspend itself. It’ll have to suspend itself listening to a mailbox , so that it can be woken up. 

You can go a step lower and use the underlying API as well as Seth (nqzero) has shown, but the principle is the same.

-sriram.

**Comment by Wonderlus** [comment]
@kilim @nqzero 

Thanks for the responses guys.

**Comment by Wonderlus** [comment]
@kilim @nqzero 

Hey guys, quick question.. I'm not sure where else to post it..

With a Continuation, is it at all possible to do something like..

```
Continuation cont = ...
if(!cont.run(100L, TimeUnit.MILLISECONDS) {
    /* continuation was timed out and yielded! */
}
```

Basically.. Is there anything we can do to make a Continuation yield if a timeout is reached?

**Comment by nqzero** [comment]
the proper place for discussion is https://groups.google.com/forum/#!forum/kilimthreads

> Is there anything we can do to make a Continuation yield if a timeout is reached?

no

thought experiment: if i needed to run arbitrary code and prevent it from blocking or hogging cpu, i'd run it in a separate jvm process and then i could just kill the external jvm. but that's well outside the scope of kilim

**Comment by kilim** [comment]
> On 7 Jul 2017, at 19:20, Cylus <notifications@github.com> wrote:
> 
> @kilim <https://github.com/kilim> @nqzero <https://github.com/nqzero>
> Hey guys, quick question.. I'm not sure where else to post it..
> 
> With a Continuation, is it at all possible to do something like..
> 
> Continuation cont = ...
> if(!cont.run(100L, TimeUnit.MILLISECONDS) {
>     /* continuation was timed out and yielded! */
> }
> Basically.. Is there anything we can do to make a Continuation yield if a timeout is reached?
> 

It is possible (theoretically) to put that feature into kilim, but it is a fair bit of work and would likely hurt performance a lot.  Basically, since this is all a cooperative tasking framework, the continuation has to periodically check if it needs to yield. That means there has to be code in every loop (in the innermost loop) and every pausable call and exit point to check if it is time to yield. The analysis required for putting this check is a bit hairy, and the runtime expense of this check everywhere can be painful. 

Instead of a general solution that hurts everyone, you can do it yourself at appropriate points. That is, before cont.run(), acquire a timestamp (currentTimeMillis()) and record it in a task specific var. At periodic and appropriate places in your pausable code, insert "if (timed out) Task.pause()”.  Of course, you’ll also have to convert all non-timed Mailbox.gets() to the timed variants, like mbox.get(remainingTime()). 

—sriram
