### ISSUE TITLE
Task blocked for ever when execute put(m) and get() in no buffered kilim.Mailbox

### ISSUE THREAD

**Issue by forchid** [kilim/kilim#72]
When using no buffered Mailbox(both initSize and maxSize 0), the put(m) and get() blocked for ever. No buffered mailbox should be supported such as golang chan or java SynchronousQueue.

**Comment by nqzero** [comment]
what's the disadvantage of using a max size of 1 ?

**Comment by nqzero** [comment]
first off, sorry for the slow reply. i should be more responsive going forward

took at look at the docs for unbuffered channels in golang and looks like they're using them as a synchronization primitive. in kilim the convention would be to use two Mailboxes, one to send the value and another to be notified when the first was read. Could actually accomplish the same with two messages to a single mailbox of size one (just discard the second one). Example:

```
    public static class Unbuffered<TT> {
        static Object marker = new Object();
        private Cell<TT> cell = new Cell();
        
        public void put(TT msg) throws Pausable {
            cell.put(msg);
            cell.put((TT) marker);
        }

        public TT get() throws Pausable {
            TT first = cell.get();
            cell.get();
            return first;
        }
        
        static void demo() {
            Unbuffered<String> box = new Unbuffered();
            Task fork1 = Task.fork(() -> {
                System.out.println("unbuf: 11");
                box.put("hello");
                System.out.println("unbuf: 12");
            });
            Task fork2 = Task.fork(() -> {
                System.out.println("unbuf: 20");
                Task.sleep(1000);
                System.out.println("unbuf: 21");
                String word = box.get();
                System.out.println("unbuf: 22 + " + word);
            });
            fork1.joinb();
            fork2.joinb();
        }
    }
```
doesn't makes sense to integrate this behavior into Mailbox (or Cell) since using the existing APIs (eg, putnb) would cause breakage. but could potentially add this `Unbuffered` class to kilim

Are unbuffered channels used frequently in golang ?

**Comment by sriram-srinivasan** [comment]
Unbuffered (or synchronous) channels are the default in go, modelled after Hoare's CSP. Because they guarantee synchronisation (sender can't move forward until receiver does a handshake), it simplifies reasoning, just as a return from a procedure call signifies that it is done. You can write more composable software, because goroutines can move in lockstep.0

See Rob Pike's paper "A Concurrent Window System" based on these principles.

I was quite taken by these ideas until I started programming in Erlang, and it seemed that suddenly everything I "knew" had been challenged. Do we really _need_ a type system? Won't writing in an untyped, interpreted language be a disaster in production? Does messaging have to be synchronous? And the answer was no in all cases. And they had  complex systems in production.

Erlang has a fire and forget philosophy, and convinced me to have to have a distributed programming mindset even within one machine, for independence of failures.  And Unix pipes were buffered, for reasons of performance. So I always intended to have mailboxes to be buffered. 

It is possible that the mailbox code can be fixed to have no buffering, but I no longer recall whether it is a trivial fix. If it isn't,  my suggestion is that mailbox should be left as is, buffered, and that if a compelling case can be made for synchronous communication (*), then we can look at a special class ("Rendevouz"?) that does not have the overhead of mailbox. It makes the programmer's intention clear, and simplifies the life of whoever is maintaining it.   

(*) Other than "it is in Go, so it should be in Kilim".

**Comment by forchid** [comment]
We should make sure that the min size of a mailbox is 1 if no unbuffered mailbox in kilim.
